ViewPager and SectionsPagerAdapter
greenfox-academy/opal-gitinder-android pull request #17
Opened 2017-06-22 07:50 UTC by balintvecsey

2017-06-22 09:41 UTC, adamgyulavari requested changes

2017-06-22 09:41 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +    adapter.addFragment(new SwipingFragment(), "Swiping");
@balintvecsey strings should resources or constants

2017-06-22 09:41 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/service/SectionsPagerAdapter.java
> +  private static final List<Fragment> mFragmentList = new ArrayList<>();
@balintvecsey this shouldnt be static final

2017-06-22 09:41 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/service/SectionsPagerAdapter.java
> +  private static final List<Fragment> mFragmentList = new ArrayList<>();
initialization should be in constructor

2017-06-22 09:41 UTC, adamgyulavari commented on app/src/main/res/layout/fragment_matches.xml
> +</LinearLayout>
@balintvecsey new line at the end of file

2017-06-22 09:41 UTC, adamgyulavari commented on app/src/main/res/menu/menu_main_activity_tabbed.xml
> +</menu>
@balintvecsey this file is unnecessary

2017-06-26 15:15 UTC, adamgyulavari approved these changes

2017-06-26 15:26 UTC, adamgyulavari commented
@balintvecsey resolve conflicts

2017-06-27 07:41 UTC, balintvecsey commented
Not yet complete, because after I solved conflicts, I started to work on to join the fragments together, and I found some bug, just like on development branch earlier.

2017-06-27 13:04 UTC, balintvecsey commented
Everything is ok now :)

2017-06-28 09:39 UTC, merged