Milan matchesendpoint
greenfox-academy/opal-gitinder-android pull request #20
Opened 2017-06-27 08:04 UTC by Garlyle

2017-06-27 10:21 UTC, adamgyulavari requested changes

2017-06-27 10:21 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/response/Match.java
> +    Timestamp matched_at;
@Garlyle `long` or `Date`, check the json converters documentation what the project uses

2017-06-27 10:21 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/response/Match.java
> +        messages = new ArrayList<>();
@Garlyle no need for this type of constructor

2017-06-27 10:21 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/response/Match.java
> +        messages = new ArrayList<>();
just an empty

2017-06-27 10:21 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/ApiService.java
>    Call<SwipingResponse> swiping(@Header(value = "X-GiTinder-token") String token, @Path("username") String username, @Path("direction") Enum<Direction> direction);
@Garlyle check the api spec, the swiping response changed

2017-06-28 13:48 UTC, balintvecsey approved these changes

2017-06-28 13:48 UTC, merged