handle login
greenfox-academy/opal-gitinder-android pull request #21
Opened 2017-06-27 10:13 UTC by dorinagy

2017-06-27 10:42 UTC, adamgyulavari requested changes

2017-06-27 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/LoginActivity.java
> +    editor.putString("Token", token);
@dorinagy use constants for the key

2017-06-27 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/LoginActivity.java
> +    editor.putString("Username", username);
@dorinagy here as well

2017-06-27 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/LoginActivity.java
> +          Log.d("dev", response.body().getToken());
@dorinagy remove the logging of the actual token

2017-06-27 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/LoginActivity.java
> +    onLogin("Bond", "abcd1234");
@dorinagy nono, where do we know the github access token?

2017-06-27 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/LoginActivity.java
> +    onLogin("", "");
why?

2017-06-28 14:40 UTC, Garlyle approved these changes

2017-06-30 09:00 UTC, merged