Sync
greenfox-academy/opal-gitinder-android pull request #22
Opened 2017-06-29 07:14 UTC by Garlyle

2017-06-29 12:15 UTC, balintvecsey requested changes
resolve conflicts

2017-06-29 12:17 UTC, dorinagy commented on app/src/main/java/com/greenfox/opal/gitinder/model/response/Match.java
> +}
@Garlyle use 2 spaces for indentation pls

2017-06-29 12:17 UTC, dorinagy commented on app/src/main/java/com/greenfox/opal/gitinder/model/response/MatchesResponse.java
> +}
@Garlyle indentation

2017-07-05 09:43 UTC, adamgyulavari requested changes

2017-07-05 09:43 UTC, adamgyulavari commented on app/src/main/AndroidManifest.xml
>  </manifest>
@Garlyle new line at the end of file

2017-07-05 09:43 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/service/MatchesBroadcast.java
> +    service.getMatches("X-GiTinder-token").enqueue(new Callback<MatchesResponse>() {
@Garlyle use the token stored in the shared preferences here

2017-07-05 12:40 UTC, Garlyle commented on app/src/main/java/com/greenfox/opal/gitinder/service/MatchesBroadcast.java
> +    service.getMatches("X-GiTinder-token").enqueue(new Callback<MatchesResponse>() {
@adamgyulavari changed

2017-07-05 14:53 UTC, adamgyulavari approved these changes

2017-07-05 14:53 UTC, adamgyulavari commented
@Garlyle resolve conflicts

2017-07-05 15:33 UTC, balintvecsey approved these changes

2017-07-14 08:25 UTC, merged