Save app state on pause
greenfox-academy/opal-gitinder-android pull request #25
Opened 2017-07-04 07:12 UTC by dorinagy

2017-07-05 09:48 UTC, adamgyulavari requested changes

2017-07-05 09:48 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +    super.onPause();
@dorinagy why the super is the second?

2017-07-05 09:48 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +    saveOnPause(APP_STATE);
@dorinagy why passing the `APP_STATE`?

2017-07-05 09:48 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +    GitinderApp.app().basicComponent().inject(this);
@dorinagy why injecting here?

2017-07-05 09:48 UTC, adamgyulavari commented on app/src/test/java/com/greenfox/opal/gitinder/RobolectricTest.java
> +    assertEquals(mainActivity.timestamp, mainActivity.preferences.getString("AppState", ""));
@dorinagy use the constant key here as well

2017-07-05 14:56 UTC, adamgyulavari requested changes

2017-07-05 14:56 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +    saveOnPause();
@dorinagy its still the second

2017-07-14 08:27 UTC, adamgyulavari requested changes

2017-07-14 08:27 UTC, adamgyulavari commented on app/src/test/java/com/greenfox/opal/gitinder/RobolectricTest.java
> +    mainActivity.onPause();
@dorinagy use roboeletric shadow for pausing

2017-07-14 08:28 UTC, adamgyulavari commented
@dorinagy and resolve conflicts

2017-07-17 13:16 UTC, balintvecsey approved these changes

2017-07-17 13:16 UTC, merged