Milan connectivity
greenfox-academy/opal-gitinder-android pull request #26
Opened 2017-07-04 11:25 UTC by Garlyle

2017-07-05 09:52 UTC, adamgyulavari requested changes

2017-07-05 09:52 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +      alertDialog.setTitle("Info");
@Garlyle use string resource

2017-07-05 09:52 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +      alertDialog.setMessage("Internet not available, check your internet connectivity and try again");
@Garlyle use string resource

2017-07-05 13:46 UTC, Garlyle commented on app/src/main/java/com/greenfox/opal/gitinder/MainActivity.java
> +      alertDialog.setMessage("Internet not available, check your internet connectivity and try again");
@adamgyulavari done

2017-07-05 14:54 UTC, adamgyulavari approved these changes

2017-07-05 14:54 UTC, adamgyulavari commented
@Garlyle resolve conflicts

2017-07-14 08:26 UTC, adamgyulavari commented
@Garlyle resolve conflicts

2017-07-14 13:20 UTC, merged