Save switches states in shared preferences
greenfox-academy/opal-gitinder-android pull request #29
Opened 2017-07-05 08:39 UTC by balintvecsey

2017-07-05 10:42 UTC, adamgyulavari requested changes

2017-07-05 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/fragments/SettingsFragment.java
> +  SharedPreferences.Editor editor;
@balintvecsey order of fields should be constants, dependencies, views, other fields

2017-07-05 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/fragments/SettingsFragment.java
> +    });
@balintvecsey also you dont use actually the switches other than here, so they could be local variables

2017-07-05 10:42 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/fragments/SwipingFragment.java
> +    });
@balintvecsey why is these changes here?

2017-07-05 11:30 UTC, balintvecsey commented on app/src/main/java/com/greenfox/opal/gitinder/fragments/SwipingFragment.java
> +    });
I made this branch from balint-connected-swipe-request-to-buttons

2017-07-14 09:06 UTC, adamgyulavari requested changes

2017-07-14 09:06 UTC, adamgyulavari commented on app/src/test/java/com/greenfox/opal/gitinder/SettingsFragmentTest.java
> +    assertTrue(sharedPreferences.contains("Enable Notifications"));
@balintvecsey you should test the value of it as well

2017-07-14 09:06 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/fragments/SettingsFragment.java
> +          editor.putBoolean(getString(R.string.settings_notifications), true);
@balintvecsey these string keys doesnt have to be string resources, they are perfectly fine as constants like `TAG`

2017-07-14 09:06 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/fragments/SettingsFragment.java
> +          editor.putBoolean(getString(R.string.settings_notifications), true);
that way you can use them in the tests as well

2017-07-17 07:42 UTC, merged