Mockserver
greenfox-academy/opal-gitinder-android pull request #3
Opened 2017-06-14 14:07 UTC by Garlyle

2017-06-14 14:35 UTC, adamgyulavari requested changes

2017-06-14 14:35 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/response/StatusResponse.java
> +    String token;
@Garlyle status response doesnt contain a token a LoginResponse should

2017-06-14 14:35 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/response/LoginResponse.java
> +    public LoginResponse(String status, String token) {
@Garlyle there is no need for these constructors (unless you are using it somewhere directly), just an empty one (json conversion will need that)

2017-06-14 14:35 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/service/MockCall.java
> +public abstract class MockCall implements Call {
@Garlyle make the MockCall generic using `<T>`

2017-06-14 15:11 UTC, Garlyle commented on app/src/main/java/com/greenfox/opal/gitinder/response/StatusResponse.java
> +    String token;
StatusResponse is the class we mentioned that stores all possible variables. Other responses will inherit from that.

2017-06-14 15:12 UTC, Garlyle commented on app/src/main/java/com/greenfox/opal/gitinder/response/LoginResponse.java
> +    public LoginResponse(String status, String token) {
Currently the MockServer is using them to create responses.

2017-06-16 09:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/ApiService.java
> +    Call login(@Body LoginRequest loginRequest);
@Garlyle this should return `Call<LoginResponse>`

2017-06-16 09:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/service/MockServer.java
> +        return new MockCall() {
@Garlyle this should be also `MockCall<LoginResponse>`

2017-06-16 10:08 UTC, adamgyulavari approved these changes

2017-06-16 10:08 UTC, merged