Milan models
greenfox-academy/opal-gitinder-android pull request #9
Opened 2017-06-19 10:16 UTC by Garlyle

2017-06-19 15:17 UTC, adamgyulavari requested changes

2017-06-19 15:17 UTC, adamgyulavari commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET" />
@Garlyle duplicated line

2017-06-19 15:17 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/Profile.java
> +    String languages;
@Garlyle `languages` field is not a String, but a String array

2017-06-19 15:17 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/Profile.java
> +    String repos;
@Garlyle `repos` field is not a String, but a String array

2017-06-19 15:17 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/User.java
> +    String appToken;
@Garlyle this is not called like this

2017-06-20 14:02 UTC, adamgyulavari requested changes

2017-06-20 14:02 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/Profile.java
> +public class Profile {
@Garlyle these models supposed to be responses from the server, hence these should be there

2017-06-20 14:02 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/Profile.java
> +public class Profile {
also responses are models, so move the whole package under models

2017-06-20 14:02 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/Profile.java
> +public class Profile {
and extend `BaseResponse`

2017-06-20 14:02 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/opal/gitinder/model/Profile.java
> +public class Profile {
`model.response`

2017-06-20 17:06 UTC, Garlyle commented on app/src/main/java/com/greenfox/opal/gitinder/model/Profile.java
> +public class Profile {
@adamgyulavari Done

2017-06-21 08:39 UTC, adamgyulavari approved these changes

2017-06-21 08:39 UTC, adamgyulavari commented
@Garlyle resolve conflicts

2017-06-21 09:05 UTC, merged